// export const USER_API_END_POINT="http://localhost:4000/api/v1/user"
// export const HOTEL_API_END_POINT="http://localhost:4000/api/v1/hotels"
// export const ROOM_API_END_POINT="http://localhost:4000/api/v1/room"
// export const BOOKING_API_END_POINT="http://localhost:4000/api/v1/booking"
export const USER_API_END_POINT = "https://staynest-server-ftfp.onrender.com/api/v1/user";
export const HOTEL_API_END_POINT = "https://staynest-server-ftfp.onrender.com/api/v1/hotels";
export const ROOM_API_END_POINT = "https://staynest-server-ftfp.onrender.com/api/v1/room";
export const BOOKING_API_END_POINT = "https://staynest-server-ftfp.onrender.com/api/v1/booking";
export const STRIPE_PUBLISHABLE_KEY = import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY;
